### ISSUE TITLE
Remove unused error constructors in module Cardano.Chain.Block.Validation

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#670] opened 2019-10-22 14:39 UTC
## Background
Consensus layer now checks a number of things that were previously checked at the ledger. However there were some errors constructors left, namely:

- [ ] `ChainValidationInvalidSignature`
- [ ] `ChainValidationBlockAttributesTooLarge`
- [ ] `ChainValidationHeaderAttributesTooLarge`
- [ ] `ChainValidationDelegationPayloadError`
- [ ] `ChainValidationInvalidDelegation`
- [ ] `ChainValidationMissingHash`
- [ ] `ChainValidationUnexpectedGenesisHash`
- [ ] `ChainValidationSignatureLight`
- [ ] `ChainValidationTooManyDelegations`

## Proposed Solution

Remove them.

**Comment by mrBliss** [comment] 2019-10-22 14:44
There are more unused constructors: 
* `ChainValidationBlockAttributesTooLarge`
* `ChainValidationHeaderAttributesTooLarge`
* `ChainValidationDelegationPayloadError`
* `ChainValidationInvalidDelegation`
* `ChainValidationMissingHash`
* `ChainValidationUnexpectedGenesisHash`
* `ChainValidationSignatureLight`
* `ChainValidationTooManyDelegations`

**Comment by dnadales** [comment] 2019-10-22 16:15
Thanks @mrBliss I will edit the issue description.

**Comment by mrBliss** [comment] 2020-02-05 08:41
Duplicate of #575.

**Closed as completed by mrBliss** 2020-02-05 08:41 UTC
Labels: duplicate, good first issue, technical-debt
